### PR TITLE
Fixes #54, at least there is not exception when out of moves

### LINKED ISSUE #54: Null pointer exceptions are sometimes thrown thrown by javaFX
Game continues to work when this happens

### PR DESCRIPTION
**Pull request by jangerritharms**
Can you guys check if this fixes the bug? I didn't get any exceptions when game is over. <bug

### CODE REVIEW

**Comment by lange88** [comment]
I cannot replicate the exceptions anymore, nice work! Can you resolve the merge conflicts and push it again?

**Comment by lange88** [comment]
I still got an exception after getting a highscore:

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: showAndWait is not allowed during animation or layout processing
	at javafx.scene.control.Dialog.showAndWait(Dialog.java:328)
	at nl.tudelft.bejeweled.game.BejeweledGame.stop(BejeweledGame.java:149)
	at nl.tudelft.bejeweled.game.BejeweledGame.boardOutOfMoves(BejeweledGame.java:241)
	at nl.tudelft.bejeweled.board.Board.outOfMoves(Board.java:640)
	at nl.tudelft.bejeweled.board.Board.checkBoardCombos(Board.java:359)
	at nl.tudelft.bejeweled.board.Board.update(Board.java:767)
	at nl.tudelft.bejeweled.game.BejeweledGame.updateLogic(BejeweledGame.java:209)
	at nl.tudelft.bejeweled.game.Game$1.handle(Game.java:77)
	at nl.tudelft.bejeweled.game.Game$1.handle(Game.java:71)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:226)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:167)
```

**Comment by lange88** [comment]
try moving the stop() at the end of outOfMoves() to the onFinished handler of the FadeTransision and you can still see the board that caused the exception. I just got an exception while the board clearly has some moves that are still possible. weird..

**Comment by jangerritharms** [comment]
This should be merageable now. It should fix #54 and #61. Can someone test it and see if they encounter any exceptions or early game overs? <bug

**Comment by lange88** [comment]
Did not get any exceptions on two occasions where I got a highscore and the board was genuinly out of moves. Looks like both bugs are fixed!

**Pull request merged**
